### ISSUE TITLE
Grapic glitches or crashes after latest game update

### ISSUE THREAD

**Issue by Wotasu** [Caradog/XI-View#25] opened 2021-01-12 09:47 UTC
New Npc in all cities close to mog house "A.M.A.N Liasion" seems to make the game either crash or get grapic glitches when you are close to it

**Comment by camosaan** [comment] 2021-01-12 14:25
Just as a follow up; when loading via XiPivot there's no issue, only with **replacing** dats on disk.

**Comment by Kingfisher1980** [comment] 2021-01-12 22:26
> Just as a follow up; when loading via XiPivot there's no issue, only with **replacing** dats on disk.

Definitely still an issue on XI pivot on Ashita. Just crashed when approaching the Bastok NPC.

**Comment by Caradog** [comment] 2021-01-13 15:08
Thanks for the report and apologies for the slow response.

I've taken a look at the update files and I can see the issue, unfortunately I'm unable to fix it right now as I've no access to a dds editor on my laptop - as soon as I'm able I will issue a fix

**Comment by camosaan** [comment] 2021-01-13 15:58
> 
> 
> > Just as a follow up; when loading via XiPivot there's no issue, only with **replacing** dats on disk.
> 
> Definitely still an issue on XI pivot on Ashita. Just crashed when approaching the Bastok NPC.

Sorry...I always forget about Ashita!

**Comment by phlare** [comment] 2021-01-16 16:58
Windower freezing when Quetzalcoatl pops every time now too, is that related?

**Comment by cawks** [comment] 2021-02-02 16:37
is there a fix for this yet?

**Comment by BuechlerA** [comment] 2021-02-23 23:29
i get some red screen artifacts (basically the skybox turns solid red) close to metalworks in bastok is this related to the A.M.A.N. liaison crash?

and there is z-fighting on the flags/emblems at bastok west gate, but I'm not sure if this is actually caused by XIView

**Comment by Shylo-Musgrove** [comment] 2021-03-10 17:17
This is still crashing. It seems I cannot get into the mh in the 3 main cities. I can confirm *multiple* crashes in Port and Southern Sandy as well as Port Bastok and Bastok Mines. I originally thought it was my HD pack but after unloading everything XI-View was the first I added back and I immediately started crashing again. I have removed the files from the main directory and am now using XI-Pivot but now I lose quite a bit of the features that I like from XI-View.

**Comment by palladin9479** [comment] 2021-03-16 12:48
just confirmed that 51.DAT is causing the game to crash and that AMAN NPC in Port Bastok doesn't have the right icons when XI-View is loaded.

**Comment by palladin9479** [comment] 2021-03-16 13:06
Ok was able to do a workaround by using ChangeTex to extract the font from XI-View 51.dat and inserting that font into the new FFXI 51.dat, then place that updated 51.dat inside FFXI's ROM\119.  I then use XIPivot to do dynamic loading of XI-View which gets me most of everything else.

**Comment by Caradog** [comment] 2021-06-09 16:59
It's long overdue, and my deepest apologies for it - life just gets in the way sometimes. Latest push should fix the issues (I'm aware there's another update tomorrow and I'll be keeping an eye on it).

**Closed as completed by Caradog** 2021-06-09 16:59 UTC
